version: '3.9'
services:
  app:
    container_name: paraf
    restart: unless-stopped
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - .:/var/www
    environment:
      - REDIS_HOST=redis
      - MONGODB_HOST=mongodb
    depends_on:
      - redis
      - mongodb
    networks:
      - app_network
      
  nginx:
    working_dir: /var/www
    container_name: nginx
    image: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker:/etc/nginx/conf.d
    networks:
      - app_network

  queue:
    container_name: queue
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php /var/www/artisan queue:work'
    depends_on:
      - mongodb
      - redis
    networks:
      - app_network

  redis:
    container_name: redis
    image: redis
    volumes:
      - ./docker/volumes/redis:/data
    ports:
      - '6363:6379'
    networks:
      - app_network

  mongodb:
    container_name: mongodb
    image: mongo:latest
    volumes:
      - ./docker/volumes/mongodb:/data
    ports:
      - '27018:27017'
    networks:
      - app_network

networks:
  app_network:
    driver: bridge